name: Run python.py

on:
  push:
    branches:
      - main
    paths:
      - python.py  # Only run if python.py is changed

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run python.py
        run: python python.py

